### ISSUE TITLE
API file naming

### ISSUE THREAD

**Issue by cjessett** [Chrismmint/Expresso#3]
(Subtlety) Instead of naming the entry api file `apiRouter.js`, name it `index.js`. This way when you reference it from your server file you can just use `require('/api')`. Node will automatically look for an `index.js` file in that directory. This is a common convention.

For reference, [you can read more about](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8) how `require` works.

Also, it is conventional in the JavaScript community to use camelCase instead of dashes for naming. So instead of `menu-items.js` you would use `menuItems.js`. Especially since that's [what you use in the name of the router](https://github.com/Chrismmint/Expresso/blob/fb2a8989cbc2f2d0b2eef5984bdee6ca4f27de36/api/menus.js#L11).

**Comment by Chrismmint** [comment]
Done
